monorepo_root = true

[monorepo]
config_roots = [
  "profile-readme",
  "blogs",
  "blogs/*",
  "logo",
  "website",
  "libs/*",
  "look-and-feel",
  "assets/*",
  "cv",
]
lockfile = true

[settings]
experimental = true
lockfile = true

[env]
MISE_EXPERIMENTAL = true
TYPST_FONT_PATHS = "{{ config_root }}/fonts"
TYPST_ROOT = "{{ config_root }}"
TIMERERTIM_REPO_ROOT = "{{ config_root }}"
'_'.file = [
  "config/values.json"
]

[vars]
REPO_ROOT = "{{ config_root }}"

[tools]
typst = "0.15"
uv = "0.12"
jujutsu = "latest"

[tasks."fmt:typst"]
description = "Format all Typst files in the repository"
tools.typstyle = "0.15"
run = [
  "typstyle -i ./ --timing",
]
