experimental_monorepo_root = true

[monorepo]
config_roots = [
  "profile-readme",
  "blogs",
  "blogs/*",
  "logo",
]

[settings]
experimental = true
lockfile = true

[env]
MISE_EXPERIMENTAL = true
TYPST_FONT_PATHS = "{{ config_root }}/fonts"
TYPST_ROOT = "{{ config_root }}"

[vars]
REPO_ROOT = "{{ config_root }}"

[tools]
typst = "0.14.2"

[tasks."fmt:typst"]
description = "Format all Typst files in the repository"
tools.typstyle = "latest"
run = [
  "typstyle -i ./ --timing",
]