experimental_monorepo_root = true

[monorepo]
config_roots = [
  "profile-readme",
  "blogs",
  "blogs/*",
  "logo",
  "website",
  "libs/*",
  "look-and-feel",
  "assets/*",
  "cv",
]

[settings]
experimental = true
lockfile = true

[env]
MISE_EXPERIMENTAL = true
TYPST_FONT_PATHS = "{{ config_root }}/fonts"
TYPST_ROOT = "{{ config_root }}"
TIMERERTIM_REPO_ROOT = "{{ config_root }}"
'_'.file = [
  "config/values.json"
]

[vars]
REPO_ROOT = "{{ config_root }}"

[tools]
typst = "0.14.2"
uv = "0.11.7"
jujutsu = "0.41.0"

[tasks."fmt:typst"]
description = "Format all Typst files in the repository"
tools.typstyle = "latest"
run = [
  "typstyle -i ./ --timing",
]
