

["prepare:output_dir"]
description = "Prepare the output directory"
dir = "{{ vars.REPO_ROOT }}"
run = [
  "mkdir -p out/blogs/{{ config_root | basename }}/web"
]

["export"]
description = "Export the blog in all formats"
depends = ["export:?*"]

["export:downloadable-pdf"]
description = "Export the blog as a downloadable PDF"
depends = ["prepare:output_dir"]
run = [
  "typst compile --format pdf --pdf-standard a-3u main.typ '{{ vars.REPO_ROOT }}/out/blogs/{{ config_root | basename }}/main.pdf'"
]

["export:web-format"]
description = "Export the blog as format for embedding in web"
depends = ["prepare:output_dir"]
run = [
  'typst-ts-cli compile -e main.typ --workspace {{ env.TYPST_ROOT }} --output "{{ vars.REPO_ROOT }}/out/blogs/{{ config_root | basename }}/web" --format svg_html --input theme=dark --input x-page-width=1024pt --input x-export-type=web',
]

