[tools]
"cargo:https://github.com/Myriad-Dreamin/typst.ts" = { version = "tag:v0.7.0-rc2", crate = "typst-ts-cli" }
typst = "0.14.2"

[task_config]
includes = [
    "tasks/scripts"
]

[tasks."export-all"]
description = "Export all blogs as pdf"
depends = ["//blogs/...:export:pdf"]

# TODO: Investigate applying task templates for the workflow
