#:schema https://mise.en.dev/schema/mise-task.json

["prepare:website-dist-dir"]
description = "Prepare the website output directory"
dir = "{{ vars.REPO_ROOT }}"
run = ["mkdir -p dist/website/api/blogs/{{ config_root | basename }}/"]

["prepare:website-build-dir"]
description = "Prepare the website build directory"
dir = "{{ vars.REPO_ROOT }}"
run = ["mkdir -p build/website/blogs/{{ config_root | basename }}/"]

["website-embedding"]
description = "Embed the blog in the website build directory"
depends = ["website-embedding:?*"]

["website-embedding:pdf"]
description = "Add the blog pdf to the website build directory"
depends = ["prepare:website-build-dir", "export:pdf"]
run = ["cp build/main.pdf {{ vars.REPO_ROOT }}/build/website/blogs/{{ config_root | basename }}/{{ config_root | basename }}.pdf"]

["website-embedding:export"]
description = "Export the all website embedding files"
depends = ["prepare:website-build-dir", "export:metadata"]
depends_post = ["website-embedding:compress"]
env.REPO_ROOT = "{{ vars.REPO_ROOT }}"
file = "{{ vars.REPO_ROOT }}/website/tasks/scripts/embed-blog.py"

["website-embedding:compress"]
description = "Compress the website embedding files using brotli"
dir = "{{ vars.REPO_ROOT }}/build/website/blogs/{{ config_root | basename }}"
sources = ["*.svg"]
outputs = ["*.svg.br"]
env.REPO_ROOT = "{{ vars.REPO_ROOT }}"
file = "{{ vars.REPO_ROOT }}/website/tasks/scripts/compress-blog.py"
